name: build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'examples/**'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'examples/**'
      - 'README.md'
  workflow_dispatch: {}

jobs:
  changes:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    outputs:
      build: ${{ steps.filter.outputs.build }}
      src: ${{ steps.filter.outputs.src }}
      e2e: ${{ steps.filter.outputs.e2e }}
      docs: ${{ steps.filter.outputs.docs }}

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            build:
              - '*'
              - 'build/**'
            src:
              - 'packages/**'
            e2e:
              - 'cypress/**'
            docs:
              - 'docs/**'

  build:
    needs: changes

    if: ${{ github.event_name == 'workflow_dispatch' || needs.changes.outputs.build == 'true' || needs.changes.outputs.src == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: setup
        uses: ./.github/workflows/shared/setup

      - name: build
        run: yarn ci:build

      - name: test summary
        uses: phoenix-actions/test-reporting@v16
        if: ${{ !cancelled() }}
        with:
          name: build
          output-to: step-summary
          path: 'packages/*/reports/mocha.json,build/reports/mocha.json'
          reporter: mocha-json

  e2e:
    needs: [changes, build]

    if: ${{ always() && !contains(needs.*.result, 'failure') && !startsWith(github.head_ref, 'dependabot') && (github.event_name == 'workflow_dispatch' || needs.changes.outputs.build == 'true' || needs.changes.outputs.src == 'true' || needs.changes.outputs.e2e == 'true') }}

    runs-on: ubuntu-latest

    steps:
      - name: start e2e workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: e2e

  docs:
    needs: [changes, build]

    if: ${{ always() && !contains(needs.*.result, 'failure') && !startsWith(github.head_ref, 'dependabot') && (github.event_name == 'workflow_dispatch' || needs.changes.outputs.build == 'true' || needs.changes.outputs.docs == 'true') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: setup
        uses: ./.github/workflows/shared/setup
        with:
          turbo-cache: 'false'

      - name: build
        run: yarn doc:build
