name: close-milestone
run-name: Close milestone ${{ github.ref_name }}

on:
  release:
    types: [published]

env:
  RELEASE_LINK: "[version ${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }})"

jobs:
  close:
    if: ${{ github.repository == 'mistic100/Photo-Sphere-Viewer' }}

    runs-on: ubuntu-latest

    steps:
      - name: Get milestone
        id: milestone
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          milestone_number="$(gh api \
            "/repos/${{ github.repository }}/milestones" \
            --jq '.[] | select(.title == "${{ github.ref_name }}") | .number' \
            | head -n 1)"
          if [ -n "$milestone_number" ]; then
            echo "milestone-number=$milestone_number" >> "$GITHUB_OUTPUT"
          fi

      - if: steps.milestone.outputs.milestone-number
        uses: bflad/action-milestone-comment@v2
        with:
          milestone: ${{ steps.milestone.outputs.milestone-number }}
          body: |
            This feature/bug fix has been released in ${{ env.RELEASE_LINK }}.

      - if: steps.milestone.outputs.milestone-number
        name: Close milestone
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method PATCH \
            /repos/${{ github.repository }}/milestones/${{ steps.milestone.outputs.milestone-number }} \
            -f description="Released in ${{ env.RELEASE_LINK }}" \
            -f state="closed"
